run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  relative-path-mode: gomod

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - misspell
      text: "`thn` is a misspelling of `then`"
    - path: pkg/messages/message.go
      linters:
        - gosec
      text: "G101: Potential hardcoded credentials"

linters:
  disable-all: true
  enable:
    - bodyclose
    - errorlint
    - errcheck
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - noctx
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - typecheck
    - unconvert
    - unused

linters-settings:
  misspell:
    locale: US
